export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  CREATE_PRODUCTS: "CREATE_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  DELETE_PRODUCTS: "DELETE_PRODUCTS",
  UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  USER_REGISTER_PENDING: "USER_REGISTER_PENDING",
  USER_LOGIN_PENDING: "USER_LOGIN_PENDING",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
};
